# Generated by Django 4.0 on 2022-01-17 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('mobile', models.CharField(default=0, max_length=12, null=True)),
                ('password', models.CharField(default=0, max_length=128, null=True)),
                ('fullname', models.CharField(default=None, max_length=100, null=True)),
                ('otp', models.CharField(default=None, max_length=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('cur_category', models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN'), ('BTC', 'BTC')], default=0, max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('category', models.CharField(choices=[('Noobs', 'Noobs'), ('Elite', 'Elite')], default=0, max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountSetup',
            fields=[
                ('wallet_address', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('currency_types', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ewallet.currency')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ewallet.user')),
                ('user_types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ewallet.usercategory')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(default=None, max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency_types', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ewallet.currency')),
                ('user_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ewallet.user')),
                ('wallet_address', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ewallet.useraccountsetup')),
            ],
        ),
        migrations.CreateModel(
            name='FundWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=50, null=True)),
                ('currency_types', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ewallet.currency')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ewallet.user')),
                ('wallet_address', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ewallet.useraccountsetup')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ewallet.fundwallet')),
            ],
        ),
    ]
