# Generated by Django 4.0 on 2022-01-17 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='wallet_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ewallet.fundwallet', unique=True),
        ),
    ]
