# Generated by Django 4.0 on 2022-01-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0002_alter_balance_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='wallet_address',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
