# Generated by Django 4.0 on 2022-01-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0003_alter_balance_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='wallet_address',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
