# Generated by Django 4.0 on 2022-01-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0004_balance_balance_alter_balance_wallet_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='balance',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ewallet.fundwallet'),
        ),
    ]
